spring.application.name=picpay
spring.datasource.url=jdbc:postgresql://localhost:5432/picpay
spring.datasource.username=postgres
spring.datasource.password=kappa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
